
interface Module {
  ver?: number;
  hierarchy?: number;
  subModuleCount: number;
  assigneeCount?: number;
  searchKey?: string;
  modifiedByUname?: string;
  title: string;
  scriptCount: number;
  executionOrder?: number;
  createdByUname?: string;
  parentId?: string;
  path: string;
  expanded: boolean;
  modifiedOn: string;
  parentName?: string;
  moduleLevelScriptCount?: number;
  lastExecutionOrder?: number;
  imported?: boolean;
  name?: string;
  modifiedBy?: string;
  moduleCountWithScript?: number;
  state?: string;
  key?: string;
  folder?: boolean;
  children?: Module[];
}
const data: Module[] = [
  {
    subModuleCount: 11,
    title: 'Root Module',
    scriptCount: 0,
    path: '/Root',
    expanded: false,
    modifiedOn: '19-12-2023 15:32',
    children: [
      {
        subModuleCount: 7,
        title: 'Home',
        scriptCount: 0,
        path: '/Root/Home',
        expanded: false,
        modifiedOn: '19-12-2023 15:43',
        children: [
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1003',
            modifiedByUname: '--',
            title: 'Setup',
            scriptCount: 0,
            executionOrder: 1,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Setup',
            expanded: false,
            modifiedOn: '19-12-2023 16:40',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Setup',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1003',
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1004',
            modifiedByUname: '--',
            title: 'Authoring Cycle',
            scriptCount: 0,
            executionOrder: 2,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Authoring Cycle',
            expanded: false,
            modifiedOn: '19-12-2023 16:40',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Authoring Cycle',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1004',
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1005',
            modifiedByUname: '--',
            title: 'Review Cycle',
            scriptCount: 0,
            executionOrder: 3,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Review Cycle',
            expanded: false,
            modifiedOn: '19-12-2023 16:41',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Review Cycle',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1005',
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1006',
            modifiedByUname: '--',
            title: 'Approval Cycle',
            scriptCount: 0,
            executionOrder: 4,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Approval Cycle',
            expanded: false,
            modifiedOn: '19-12-2023 16:41',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Approval Cycle',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1006',
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1007',
            modifiedByUname: '--',
            title: 'Approved Not Effective Cycle',
            scriptCount: 0,
            executionOrder: 5,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Approved Not Effective Cycle',
            expanded: false,
            modifiedOn: '19-12-2023 16:46',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Approved Not Effective Cycle',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1007',
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1008',
            modifiedByUname: '--',
            title: 'Approved And Effective Cycle',
            scriptCount: 0,
            executionOrder: 6,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Approved And Effective Cycle',
            expanded: false,
            modifiedOn: '19-12-2023 16:46',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Approved And Effective Cycle',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1008',
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1009',
            modifiedByUname: '--',
            title: 'Date of Final Approval Cycle',
            scriptCount: 0,
            executionOrder: 7,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Date of Final Approval Cycle',
            expanded: false,
            modifiedOn: '19-12-2023 16:57',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Date of Final Approval Cycle',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1009',
          },
        ],
        lastExecutionOrder: 7,
        imported: false,
        modifiedBy: '--',
        moduleCountWithScript: 0,
        state: 'NEW',
        key: 'MOD1002',
        ver: 1,
        hierarchy: 1,
        assigneeCount: 0,
        searchKey: '/MOD1001/MOD1002',
        modifiedByUname: '--',
        executionOrder: 1,
        createdByUname: 'Shivaprasad',
        parentId: 'MOD1001',
        parentName: 'Root Module',
        folder: true,
        moduleLevelScriptCount: 0,
        name: 'Home',
      },
      {
        subModuleCount: 1,
        title: 'Test',
        scriptCount: 0,
        path: '/Root/Test',
        expanded: false,
        modifiedOn: '10-01-2024 20:56',
        children: [
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1021/MOD1022',
            modifiedByUname: '--',
            title: 'Login',
            scriptCount: 0,
            executionOrder: 1,
            createdByUname: 'Natacha',
            parentId: 'MOD1021',
            path: '/Root/Test/Login',
            expanded: false,
            modifiedOn: '10-01-2024 20:57',
            parentName: 'Test',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Login',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1022',
          },
        ],
        lastExecutionOrder: 1,
        imported: false,
        modifiedBy: '--',
        moduleCountWithScript: 0,
        state: 'NEW',
        key: 'MOD1021',
        ver: 1,
        hierarchy: 1,
        assigneeCount: 0,
        searchKey: '/MOD1001/MOD1021',
        modifiedByUname: '--',
        executionOrder: 2,
        createdByUname: 'Natacha',
        parentId: 'MOD1001',
        parentName: 'Root Module',
        folder: true,
        moduleLevelScriptCount: 0,
        name: 'Test',
      },
      {
        ver: 1,
        hierarchy: 1,
        subModuleCount: 0,
        assigneeCount: 0,
        searchKey: '/MOD1001/MOD1024',
        modifiedByUname: '--',
        title: 'Others',
        scriptCount: 0,
        executionOrder: 3,
        createdByUname: 'Solabs',
        parentId: 'MOD1001',
        path: '/Root/Others',
        expanded: false,
        modifiedOn: '18-01-2024 16:14',
        parentName: 'Root Module',
        folder: true,
        moduleLevelScriptCount: 0,
        lastExecutionOrder: 0,
        imported: false,
        name: 'Others',
        modifiedBy: '--',
        moduleCountWithScript: 0,
        state: 'NEW',
        key: 'MOD1024',
      },
    ],
    lastExecutionOrder: 3,
    imported: false,
    modifiedBy: '--',
    moduleCountWithScript: 1,
    state: 'NEW',
    key: 'MOD1001',
    ver: 1,
    hierarchy: 0,
    assigneeCount: 0,
    searchKey: '/MOD1001',
    modifiedByUname: '--',
    executionOrder: 0,
    createdByUname: 'Shivaprasad',
    folder: true,
    moduleLevelScriptCount: 0,
    name: 'Root Module',
  },
];

export default data;
